apiVersion: apps/v1
kind: Deployment
metadata:
  name: animea-meetings
spec:
  selector:
    matchLabels:
      app: animea-meetings
  replicas: 1
  template:
    metadata:
      labels:
        app: animea-meetings
    spec:
      containers:
      - name: envar-demo-container
        image: animea/animea-meetings
        ports:
        - containerPort: 3002
        env:
        - name: SERVER_IP
          value: '185.176.5.147'
        - name: GATEWAY_PORT
          value: '7401'
          
---
apiVersion: v1
kind: Service
metadata:
  name: animea-meetings
spec:
  selector:
    app: animea-meetings
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31000
  type: NodePort