apiVersion: v1
kind: Service
metadata:
  name: animea-meetings
spec:
  selector:
    app: animea-meetings
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31000
  type: NodePort